### ISSUE TITLE
Unable to register account

### ISSUE THREAD

**Issue by JoeanAmier** [greasyfork-org/greasyfork#1224]
![image](https://github.com/JasonBarnabe/greasyfork/assets/49263334/bd1edc1a-8d18-43b0-91f3-c5360b9a2f3c)

Whenever I register an account, I will be prompted with these

**Comment by JoeanAmier** [comment]
reCAPTCHA verification failed, please try again.

**Comment by JasonBarnabe** [comment]
reCAPTCHA blocked in your country maybe? (But there are many Chinese users so I don't know...)

**Comment by japan228866** [comment]
> reCAPTCHA blocked in your country maybe? (But there are many Chinese users so I don't know...)

YOU MOTH** FU**

You banned the account at will without any warning. The reason is too subjective.

**Comment by japan228866** [comment]
> reCAPTCHA blocked in your country maybe? (But there are many Chinese users so I don't know...)

💩💩💩💩💩💩💩

**Comment by japan228866** [comment]
> reCAPTCHA blocked in your country maybe? (But there are many Chinese users so I don't know...)

You 1d1ot 😂
