### ISSUE TITLE
Feedback Section should show the latest discussion instead of the starter

### ISSUE THREAD

**Issue by cyfung1031** [greasyfork-org/greasyfork#1241]
For example

<img width="1091" alt="Screen Shot 2024-02-04 at 17 13 19" src="https://github.com/JasonBarnabe/greasyfork/assets/44498510/871d7054-1869-40fb-9810-a54ab03a82ae">

<img width="1199" alt="Screen Shot 2024-02-04 at 17 13 28" src="https://github.com/JasonBarnabe/greasyfork/assets/44498510/4c92f41c-fde4-4dd8-977e-29728110f8b7">

The issue is already resolved. The list of feedback should not show the first comment inside the discussion.
It should show the last comment as it is resolved.

**Comment by JasonBarnabe** [comment]
The first comment is a better indicator of the topic of the discussion than the last comment.
