### ISSUE TITLE
Weird Script Comparison `@downloadURL none`

### ISSUE THREAD

**Issue by cyfung1031** [greasyfork-org/greasyfork#1242]
https://greasyfork.org/en/scripts/19256-google-to-youtube-search/diff?v1=1321205&v2=1243245&context=3&w=1&terser=1

The script does not change `@downloadURL` between 6.5 and 6.2
This should be a bug.

**Comment by JasonBarnabe** [comment]
The diff works off the original code as provided by the author. This is simply a change that they made for whatever reason.

The code served up by the site for installation will rewrite `@downloadURL`.
