### ISSUE TITLE
[Feature Request] Automatic script sets should be multiple conditions

### ISSUE THREAD

**Issue by cyfung1031** [greasyfork-org/greasyfork#1247]
Now we have

Scripts for site (e.g. example.com, leave blank for "All sites") 
Scripts by user (URL, ID, or name)

but these two shall work together.

So We can auto get the scripts for a domain written by a userscript.

* Condition A and Condition B

**Comment by adamlui** [comment]
I agree this is an important feature and something I wished for years now

**Comment by JasonBarnabe** [comment]
Script sets is a legacy feature that I'm leaving for those already using it. I'm not going to be developing it further.
