### ISSUE TITLE
Requesting account unblocking

### ISSUE THREAD

**Issue by MoTeam-org** [greasyfork-org/greasyfork#1252]
My account was banned due to being associated with some internet celebrities. I did not respond to this report due to some issues, which resulted in my account being banned. I hope to have my account unblocked. As my script is stored on this account, can I unblock it?

https://greasyfork.org/en/reports/62005

![image](https://github.com/greasyfork-org/greasyfork/assets/112475198/9b56d053-69d6-498f-9737-61e8a9be17ee)

**Comment by JasonBarnabe** [comment]
Looks like you deleted the user, there is no recovery from that.
