### ISSUE TITLE
Problem whit share a script

### ISSUE THREAD

**Issue by Cristianboy9** [greasyfork-org/greasyfork#1256]
Hello, im triying to share a script and say is a copy from other code but is deleted the other code so is impossible i copy tipos can u fix información me can publishing the script?

**Comment by JasonBarnabe** [comment]
If you didn't write the script yourself and don't have the license to do so, then it's not allowed on Greasy Fork.

If you're claiming you did write the script yourself, then please provide a link to it and I'll check to see what existing script is preventing the submission.

**Comment by Cristianboy9** [comment]
Is coded by my Friend the Last Day and is impossible copy cuz is deleted for years

**Comment by JasonBarnabe** [comment]
You'll need to provide evidence that you're the original author, otherwise it will remain blocked.
