### ISSUE TITLE
The recommended software link on the website homepage (Android) cannot be opened

### ISSUE THREAD

**Issue by rourou007** [greasyfork-org/greasyfork#1257]
“书签地球”的安装官方链接更换了
最新的应该是：https://www.bookmarkearth.cn/download/app

The official installation link for Bookmark Earth has been changed
The latest should be: https://www.bookmarkearth.cn/download/app
![123123](https://github.com/greasyfork-org/greasyfork/assets/156311326/0cf5a986-67e9-470d-bbe0-5fc61abd37fd)

**Comment by JasonBarnabe** [comment]
Thanks for the heads up.
