### ISSUE TITLE
Webhooks cannot be edited

### ISSUE THREAD

**Issue by adamlui** [greasyfork-org/greasyfork#1269]
There's no way to edit webhooks once created, I had to go to script page, "Turn off syncing" to get webhook to disappear from https://greasyfork.org/en/users/webhook-info, go to GitHub repo > Settings > Webhooks, delete GF webhook, confirm, Add webhook, fill in payload URL, update content-type, fill in secret, Add webhook, and even then it's unclear what is the URL it's going to try to sync with

_Originally posted by @adamlui in https://github.com/greasyfork-org/greasyfork/issues/1253#issuecomment-2148191440_

**Comment by adamlui** [comment]
I went to https://greasyfork.org/en/scripts/460805-autoclear-chatgpt-history/admin and filled in raw user.js URL to get webhook to finally show up in https://greasyfork.org/en/users/webhook-info but the issue remains, existing webhooks simply cannot be edited without going thru the aforementioned arduous process

**Comment by adamlui** [comment]
Previous to all this I clicked "Turn off syncing for this script" because there was no way to edit URLs is how I got to the URL add step again, so the URL should be editable directly on that page instead (similar to "URL of script to promote")

**Comment by adamlui** [comment]
I don't mind doing hard work I am only looking out for the interests of lazy other users

**Comment by adamlui** [comment]
Also I tested your last update of allowing unraw URL for update by de-activating BraveGPT sync, then re-adding the URL, then in Webhooks page it shows this:

![image](https://github.com/greasyfork-org/greasyfork/assets/10906554/c538b938-63de-411a-b1a8-7c9f9bd125a7)

**Comment by adamlui** [comment]
> Also I tested your last update of allowing unraw URL for update by de-activating BraveGPT sync, then re-adding the URL, then in Webhooks page it shows this:
> 
> ![image](https://private-user-images.githubusercontent.com/10906554/336610932-c538b938-63de-411a-b1a8-7c9f9bd125a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1MzYyNzksIm5iZiI6MTcxNzUzNTk3OSwicGF0aCI6Ii8xMDkwNjU1NC8zMzY2MTA5MzItYzUzOGI5MzgtNjNkZS00MTFhLWIxYTgtN2M5ZjliZDEyNWE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDIxMTkzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3OGUxMGNmYjU2M2Q3NzNjZmY5NmExOGRiZmFiNjc1ZTQ0MGJmNTY4MjFkNDY5MzBhMzRjZjQ0NGEwYzA4MGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GjICIc1LKIG8sjuXxLvgJKrOiUYnhIyL9UqbbjSlnR0)

Actually this bug occurs for if raw URL is added too, the issue is if user did not select "Automatic" or "Manual" (which they don't expect to if merely supplying a URL for webhook to use) then name var is empty

![image](https://github.com/greasyfork-org/greasyfork/assets/10906554/6de567b0-0722-4d20-a859-52d8b011de8c)

**Comment by adamlui** [comment]
To better explain, this is what user sees in script admin if webhook is working:

![image](https://github.com/greasyfork-org/greasyfork/assets/10906554/d4399c80-1751-4d16-8f97-a3d0d55403b0)

There is no way to change webhook sync src URL. User has to click 'Turn off syncing for this script' then it reverts to unsynced interface:

![image](https://github.com/greasyfork-org/greasyfork/assets/10906554/4888e714-e641-433d-8202-a8e7f85d31ad)

Then, working webhook is removed from the https://greasyfork.org/en/users/webhook-info page.

Then, to set up a new webhook again, user must input webhook's intended sync src URL in 'To enable syncing for your script, provide a URL'

![image](https://github.com/greasyfork-org/greasyfork/assets/10906554/ac22fa7b-1b37-4191-a45c-201c8329ae2e)

Then they must click 'Update and sync now', then the interface changes to one where URL can be editable:

![image](https://github.com/greasyfork-org/greasyfork/assets/10906554/1651cdc4-224f-42fa-9550-0e9b5c330819)

Then, the page shows the weird unnamed source glitch if they didn't pick auto/manual (since they don't expect to for setting up a webhook and this is the only way):

![image](https://github.com/greasyfork-org/greasyfork/assets/10906554/e95615e4-0a95-44a8-9a12-025707eb2898)

Then, after first webhook sync, script admin changes to remove editable URL field:

![image](https://github.com/greasyfork-org/greasyfork/assets/10906554/b78baeaf-7979-4269-b735-8abf5937f823)

... while https://greasyfork.org/en/users/webhook-info page no longer shows 'Name' for src if auto/manual wasn't selected, but accurately reflects 'Webhook'

![image](https://github.com/greasyfork-org/greasyfork/assets/10906554/ccfe81fc-5678-440c-bd5e-f64b65e01d59)

**Comment by adamlui** [comment]
So you just have to add the sync src URL field to the script admin interface where 'Webhook' is selected to fix this issue (also ideally allowing users to select 'Webhook' from script admin directtly is more intuitive than going to an account page)

**Comment by adamlui** [comment]
So to summarize, there are two issues. Currently to add webhook, a sync src URL must exist first, and the only way is to supply it in the script admin page. So the two problems are:

1. If user is using this field only for this purpose, they expect to pick 'Webhook' directly right then and there. Not seeing such option, they will not pick 'Auto' or 'Manual' and the unnamed src glitch occurs
2. After added, sync src URL is permanently uneditable since URL field disappears from script admin page

**Comment by JasonBarnabe** [comment]
#1 - this was an oversight and is fixed now.
#2 - didn't see this happen, but I made some changes to this area so maybe it's fixed. If not let me know and provide the URL of the script that's showing weird.

**Comment by adamlui** [comment]
> 2 - didn't see this happen, but I made some changes to this area so maybe it's fixed. If not let me know and provide the URL of the script that's showing weird.

It's this screenshot I provided:

![336614739-b78baeaf-7979-4269-b735-8abf5937f823](https://github.com/greasyfork-org/greasyfork/assets/10906554/2e877547-4979-444e-8d1d-6d53b8bea7ea)

There's no URL field for webhook sync src (you can always view as test user acct, it may be ages before I need to update again)

**Comment by adamlui** [comment]
(the field in the shot is for description srcs)

**Comment by JasonBarnabe** [comment]
This is always editable now, no matter how it's set up to sync.

Please take the time to understand what I'm telling you, then post one single reply if you have further comments, questions, or suggestions.

**Comment by adamlui** [comment]
Oh you got your numbers reversed then (my 1 was name syncing, 2 was URL field missing, your 1 was it is fixed, 2 was didn't see)
