### ISSUE TITLE
Too many "Down for Maintenance" since a long time

### ISSUE THREAD

**Issue by decembre** [greasyfork-org/greasyfork#1272]
I see this page in many case.
Reload the page fix it, but that's i little bit irritating:
Can you fix that ?

**Comment by JasonBarnabe** [comment]
Are you getting status 503 or something else? With a 503 the cause may be rate limiting, which you may be hitting if you open lots of tabs at once, or are hitting some specific sensitive areas too often.

**Comment by decembre** [comment]
Its randomly and different of error:
- I have not 503 or very rearely.
- It's more often the "down for maintenance "
- but can be a simple blank page:
by example when i want post in forum) or update a script etc (often i copy my text before if it is too long to not lost it if i can't post)

**Comment by JasonBarnabe** [comment]
The message "We're down for maintenance. Check back again soon." is indicative of a 503 error. Is that what you're seeing? If not, please post the exact text or a screenshot the next time it happens.

Apart from rate limiting, it's also possible that the site is under heavy load. Looking at my graphs, I don't see any resource that's running low in the past few days, and I haven't personally seen any errors, but it's possible they're only occurring at times I'm not online.

I could also check the logs for your IP address, if you feel comfortable sending it to me. You can email it to jason.barnabe@gmail.com if you don't want to post it here.

**Comment by decembre** [comment]
As i can remember, an other user spoke to me about these "down for maintenance":
<a href="https://greasyfork.org/fr/scripts/439699-greasyfork-script-set-edit-button/discussions/241663#comment-503619">Seems the old problem is coming back again ... If you're not meeting &quot;We're down for maintenance&quot; then maybe there's another bug in script</a>

I can see in the devtool if you say to me what i need to check:
i don't know where to find logs of my IP

**Comment by JasonBarnabe** [comment]
I pulled your logs based on your most recently used IP, and I found you're hitting the rate limiter. More details [here](https://greasyfork.org/en/discussions/greasyfork/247241-am-i-alone-to-have-difficulty-to-login-in-greasy-fork#comment-507261).

**Comment by decembre** [comment]
Yes , that's:
<a href="https://greasyfork.org/fr/scripts/439699-greasyfork-script-set-edit-button">Greasyfork Set Edit+</a>

**Comment by JasonBarnabe** [comment]
The author of that script will have to make changes. I may be able to support them. See [this discussion](https://greasyfork.org/en/scripts/439699-greasyfork-script-set-edit-button/discussions/247682).

**Comment by decembre** [comment]
Thanks for your help !
