### ISSUE TITLE
No scripts found on Greasyfork platform, no violations found

### ISSUE THREAD

**Issue by AFANOOO** [greasyfork-org/greasyfork#1278]
No scripts found on Greasyfork platform, no violations found
[https://greasyfork.org/zh-CN/scripts/480255-%E7%99%BE%E5%BA%A6%E7%BD%91%E7%9B%98%E4%B8%8D%E9%99%90%E5%88%B6%E4%B8%8B%E8%BD%BD-%E7%A5%9E%E9%80%9Fdown](url)

**Comment by JasonBarnabe** [comment]
What?

**Comment by AFANOOO** [comment]
What bug is this on my script homepage that I sometimes can't see or search for

![微信截图_20240616155128](https://github.com/greasyfork-org/greasyfork/assets/124020325/3f371253-d5ec-4278-9d1d-26ba559f9f38)
![微信截图_20240616155203](https://github.com/greasyfork-org/greasyfork/assets/124020325/bdf46b36-749a-4942-844a-e644e164cd1a)

**Comment by JasonBarnabe** [comment]
Possibly the same issue as #1279, will monitor.

**Comment by AFANOOO** [comment]
> Possibly the same issue as #1279, will monitor.

This problem still exists at present

**Comment by JasonBarnabe** [comment]
I believe this is the same as #1279, which is now fixed. That bug caused scripts that were updated to disappear from the listings until the start of every hour.
