### ISSUE TITLE
Add SUSTECH & Zstatic CDN

### ISSUE THREAD

**Issue by famousprince** [greasyfork-org/greasyfork#1282]
BootCDN and StaticFile have been removed due to potential supply chain attack risks, see https://greasyfork.org/en/discussions/development/249443-polyfill-supply-chain-attack-bootcdn-and-staticfile

However, due to CDNs in the allowed list such as ByteDance and baomitu have problems such as resources too stale, and unpkg.com cdnjs.cloudflare.com blocked by ISPs or poor performace in China, I sincerely request to add `mirrors.sustech.edu.cn` and `s4.zstatic.net`.

The usage are:

`mirrors.sustech.edu.cn/cdnjs/ajax/libs/`
`s4.zstatic.net/ajax/libs`
(Just like cdnjs.cloudflare.com)

Content from these two CDNs are only synced from CDNjs and other arbitrary files are strictly disallowed, see https://mirrors.sustech.edu.cn/help/cdnjs.html and https://www.zstatic.net/.

**Comment by JasonBarnabe** [comment]
I like how the idea is to replace a CDN with a security vulnerability with one called [sus](https://www.merriam-webster.com/wordplay/what-does-sus-mean)tech.

**Comment by JasonBarnabe** [comment]
Added sustech and zstatic.
