### ISSUE TITLE
I can't receive any verification code information in my email

### ISSUE THREAD

**Issue by javaisbestlang** [greasyfork-org/greasyfork#1284]
Hello, recently because my github account was marked, I couldn't log in through github, so I applied for a new account, but the original account script still has to be updated, the password was forgotten, tried to accept the verification with the mailbox, but never received, including in the trash, resulting in me unable to update the script, please ask what is the situation

**Comment by JasonBarnabe** [comment]
What is your user ID on Greasy Fork?

**Comment by javaisbestlang** [comment]
https://greasyfork.org/zh-CN/users/944663-wuxin0011

**Comment by JasonBarnabe** [comment]
The email associated to that account is a bunch of numbers @qq.com. When Greasy Fork sends to that email address, it bounces with the message `550 Mail is rejected by recipients`.

**Comment by JasonBarnabe** [comment]
If you truly cannot receive emails from Greasy Fork for a reason outside your control, then to prove you are the owner of the account, send me (jason.barnabe@gmail.com) an email from the address associated with your Greasy Fork account.

**Comment by javaisbestlang** [comment]
### I searched for the following error causes

The content of the email is suspected of being sent in large quantities, and most users have complained about it as spam.
For mass emails, if users generally express disgust or collective complaints, Tencent Mail will prohibit the content of similar emails from being sent.

I didn't block or refuse greasyfork's mail message acceptance Maybe the Tencent server filtered this kind of email

**Comment by javaisbestlang** [comment]
No wonder I rushed to re-register an account and still didn't receive the message, so I could only log in with github

**Comment by javaisbestlang** [comment]
I've sent you a message via email, can you receive it? And then what do I do.
If you don't receive a message, you can send it here on GitHub


![image](https://github.com/user-attachments/assets/547dd0ad-1943-4a2c-b646-608f3d7307b4)

**Comment by javaisbestlang** [comment]
Okay, sorry, this is my email account alias
Okay I changed it, I sent you a message again, now you can confirm it

**Comment by javaisbestlang** [comment]
Then should I send a new email from greasyfork that I forgot my password
