### ISSUE TITLE
Wrong word used for Update button if script has anti-feature

### ISSUE THREAD

**Issue by adamlui** [greasyfork-org/greasyfork#1285]
For example, https://greasyfork.org/scripts/478597-googlegpt has the ads antifeature now, and clicking script 'Update' button leads to 'Install' button instead

![](https://github.com/user-attachments/assets/206633c4-b329-46e9-845d-c648382cafd5)

Also not as big a deal but one green button having rounded corners while the other green one has sharp corners is weird design decision. It would look a lot better if they were both sharp or rounded

**Comment by JasonBarnabe** [comment]
> Also not as big a deal but one green button having rounded corners while the other green one has sharp corners is weird design decision. It would look a lot better if they were both sharp or rounded

Install buttons are rounded now.

**Comment by JasonBarnabe** [comment]
Text of the confirm button in the anti-feature modal now is the same as the on-page install button.
