### ISSUE TITLE
Already installed scripts w/ antifeature uselessly trigger warning

### ISSUE THREAD

**Issue by adamlui** [greasyfork-org/greasyfork#1286]
![348063716-206633c4-b329-46e9-845d-c648382cafd5](https://github.com/user-attachments/assets/dabf0c6b-69d7-4a0b-b261-305e8c160a08)

This is not useful beyond a first alert unless some new antifeature got added (user already knows, do not need to see on every update)

**Comment by JasonBarnabe** [comment]
Greasy Fork does not know what anti-features the currently installed version has, so can't distinguish between antifeatures that the user has already agreed to and new ones. So to be safe, it will always show this.
