### ISSUE TITLE
Mod bizarrely dismissive of useful reports of unauthorized copies

### ISSUE THREAD

**Issue by adamlui** [greasyfork-org/greasyfork#1287]
https://greasyfork.org/en/reports/66346

![image](https://github.com/user-attachments/assets/6c86bcda-b01a-4f2a-ab42-3b2bafab2e6d)

> It's not stolen, it was mirrored 10 years ago as stated in the description.

If I wrote something and someone who I did not authorize to post my code did it, the law sees it as theft (in this case not for monetary gain but stat clout for higher profile visibility)

> At that time greasyfork didn't enforce license.

Not sure what their point here is... right now, this moment, this second, a GF report form exists for the express purpose of report unauthorized copies such as this one. Doesn't matter if licenses was enforced 10 years ago or not, we are here today right now submitting/reviewing today's form which accurately reported an uploader posted the code, an exact copy without authorization of the original author (thus it is an Unauthorized Copy)

> Now that RobWu has an account here we can remove the old script indeed.

They dismissed the report though, not sure why... if script is to be removed for unauthorized copying, then the report was actually useful and the direct cause of corrective action. Why strangely "dismiss" it? What does it even mean? (Imagine how many other reports they equally "dismiss" to potentially discourage actually helpful contributors from being vigilant like me)

**Comment by adamlui** [comment]
Also in case it was dismissed simply because the author tag credited Rob, I reported an unauthorized copy of my GoogleGPT before that too preserved original author credit, however that one was "upheld" (this encouraged me to report more unauthorized duplicates like this one so GF is less cluttered and better to use)

**Comment by JasonBarnabe** [comment]
Not sure why the report was dismissed, but it looks like https://greasyfork.org/en/scripts/6193-don-t-track-me-google got deleted anyway, so the result is the same.

Greasy Fork has always enforced license and copyright rules, but there is always the possibility that the original author authorized the repost, so we don't proactively look for these things.
