### ISSUE TITLE
Does the uploaded script show that the domain name of staticfile CDN is not on the whitelist?

### ISSUE THREAD

**Issue by MoTeam-org** [greasyfork-org/greasyfork#1289]
As the title suggests, updating the script today shows that the static file CDN domain is not on the whitelist, and I am unable to update my script. I would like to see what is going on?
![image](https://github.com/user-attachments/assets/1a98a826-ae40-4196-affd-69c53c5eec59)
![image](https://github.com/user-attachments/assets/0b0a4495-8cb5-402e-a5c7-a6955e440458)

**Comment by waahah** [comment]
https://greasyfork.org/zh-CN/help/external-scripts
别一上来就问，问之前先上官方网站看看公告和政策，国人通病

**Comment by JasonBarnabe** [comment]
> 由于潜在的供应链攻击风险，BootCDN 和 StaticFile 已被删除，请参阅
> https://greasyfork.org/en/discussions/development/249443-polyfill-supply-chain-attack-bootcdn-and-staticfile

This is correct.
