### ISSUE TITLE
Author picassoTX spamming matches and mods allow it

### ISSUE THREAD

**Issue by adamlui** [greasyfork-org/greasyfork#1290]
I open here instead of site because it unhelpfully prevents opening new reports on legit re-offenses if too recent.

picassoTX  iss stuffing matches in a script that supposedly enables copy/paste for sites that don't even disable this function.

- 1st report https://greasyfork.org/en/reports/66330 was outright "Dismissed"
- 2nd report https://greasyfork.org/en/reports/66485 was "Upheld," yet script is still live. (In report, a mod admitted "having it in the source code without being used is pointless and misleading" and instructed him to remove extraneous matches)

All he's done was remove the ten matches I exposed though, but as mentioned, probably 90% of his matches don't actually prevent copy/paste (for example, just tested [leecode-cn.com](https://leecode-cn.com), that's another site that doesn't disable copy/paste so his script is pointlessly matching except for referral link antifeature) so his script is useless on many more matches, for the dual purpose of inflating visibility to boost downloads (that's how he got so many so far) and collect revenue on those spam matches against the antifeature match rule

So a mod needs to actually enforce this rule instead of dismissing/overturning my reports by thoroughly testing his long list of matches (every one I ever randomly tested i.e. the 11 I ever did was a spam one, so it should not be hard to catch because only one is needed to confirm violation of rule)

Alternatively he should be banned because he only removed the bare minimum spam matches he thought he could get away with to test if script would be restored, which shows he doesn't care about rules since spam matches remain and don't benefit the by-site result pages thus hurts GF UX

**Comment by adamlui** [comment]
Also I think he is a Chinese friend of one of the mods (probably the first one that wrongfully dismissed teh report) who maybe even told him only remove the matches explicitly mentioned, they might be revenue sharing is why

**Comment by adamlui** [comment]
Someone restored the script again, and all he had done was remove 5 matches (3 of which were previously reported) so someone keeps helping him against the rule. I even just randomly checked another match https://blog.51cto.com/ and the site has no use for this script because it doesn't disable copy/paste.

At this point I highly suspect he's just an alt for one of the mods
- his user number is suspiciously new, how can he be this comfortable with GF gaming strategy already
- recently I alerted mods about the multi-matching in GoogleGPT, which probably gave the rogue mod this idea (except mine actually provided functionality and still was disallowed, this mod's just spamming it for the antifeature)
- his alt's username is so fake sounding (like he saw the word 'picasso' and to sound American, then picked 'TX' because Asians think of Texas when it comes to Americans)

**Comment by adamlui** [comment]
Actually I'm 99% certain this is a mod, even the description is spam that links to things like Awesome ChatGPT (which I link to in all my ChatGPT scripts but is on-topic for showing my scripts' inclusion in list) proving he probably knows me from reading my recent statement about multi-matching (which was only read by mods)

**Comment by JasonBarnabe** [comment]
Use the reporting function on the site for issues like this. The repo is for issues with Greasy Fork's own code.

**Comment by adamlui** [comment]
I said the reporting function is disabled....
