### ISSUE TITLE
Cannot update my script (502 Gateway Error)

### ISSUE THREAD

**Issue by realcoloride** [greasyfork-org/greasyfork#1292]
Hello!

My following script [YouTubeDL](https://github.com/realcoloride/YoutubeDL) cannot be updated because every time, I get the same error over and over again. It doesn't matter what I do and how I update the script, I get the same error.

VPN/No VPN doesn't do anything. Logging on/off doesn't do anything. I've tried reviewing my code and same thing. I've waited days to see if it was just a temporary issue, but I've waited long enough and I still have the same error when updating my script.

![image](https://github.com/user-attachments/assets/56fa6499-677b-4c5e-90cd-f5c1a31a9ed9)

Cheers

**Comment by JasonBarnabe** [comment]
```
1.1.1.1 - - [16/Jul/2024:03:59:58 +0000] "POST /fr/scripts/471103-youtubedl/versions HTTP/2.0" 502 568 "https://greasyfork.org/fr/scripts/471103/versions/new" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
```

```
2024/07/16 03:59:58 [error] 954#954: *536734235 upstream prematurely closed connection while reading response header from upstream, client: 1.1.1.1, server: greasyfork.org, request: "POST /fr/scripts/471103-youtubedl/versions HTTP/2.0", upstream: "http://unix:///www/greasyfork/shared/tmp/sockets/puma.sock:/fr/scripts/471103-youtubedl/versions", host: "greasyfork.org", referrer: "https://greasyfork.org/fr/scripts/471103/versions/new"
```

I do see see a process crash in the logs, but it has no timestamp or IP address attached. It's possible the script is crashing the JS checking process. Can you provide the content of the script you're trying to post?

**Comment by realcoloride** [comment]
Hello there again,
The content of the script is available here: https://github.com/realcoloride/YoutubeDL/blob/main/youtubeDL.user.js

Cheers

**Comment by JasonBarnabe** [comment]
I was able to post that without issue - https://greasyfork.org/en/scripts/500866-youtubedl - so not a JS checking problem. Perhaps something specific to your browser or account.

**Comment by realcoloride** [comment]
Perhaps its the description of the package or the patchnotes?

**Comment by JasonBarnabe** [comment]
No issues with that - https://greasyfork.org/en/scripts/500866-youtubedl

It's possible however that there is an encoding issue somewhere and posting it to GitHub, then me copy and pasting it, makes it not happen.

I would suggest trying to update just the code, then just the additional info, then doing no changes and just pressing update, to see which cases fail.

**Comment by realcoloride** [comment]
Well, that's odd. I managed to make it update by copy pasting through GitHub. Thank you, but I'm still weirded by why this is happening.

**Comment by JasonBarnabe** [comment]
My guess would be there's some encoding issue that gets fixed by the process of putting in on GitHub and copy/pasting.

When you were trying and it was failing, were you copy pasting into the text area or doing a file upload?

**Comment by realcoloride** [comment]
When it was failing I actually tried doing both multiple times, copy pasting & file upload.

**Comment by JasonBarnabe** [comment]
Another possibility is that you're hitting the rate limiter, possibly due to a user script that's doing something on Greasy Fork? I can see from your IP lots of requests to `/scripts/471103-youtubedl/versions.json`.

**Comment by realcoloride** [comment]
Yes. They check the version to see if the script is up to date and puts a yellow text to click to update at the bottom.

**Comment by JasonBarnabe** [comment]
Alright, well pretty sure that's the issue you're having. It's making requests at too high of a rate and causing your IP to be blocked for short periods. I would recommend reporting this to the author of that script.

**Comment by realcoloride** [comment]
Thank you again for helping me.
I am the author of the script.
