### ISSUE TITLE
Site code unhelpfully disables reporting scripts if recently reported

### ISSUE THREAD

**Issue by adamlui** [greasyfork-org/greasyfork#1294]
You strangely closed https://github.com/greasyfork-org/greasyfork/issues/1290 which reported this issue so I am opening as new one

**Comment by adamlui** [comment]
Primary cases where it is useless:

- Script got wrongfully restored while still in violation
- Scrip got rightfully restored, but author re-violates

**Comment by JasonBarnabe** [comment]
This is intentional to stop harassment by reporters. It applies only when reports are dismissed or still pending.

**Comment by adamlui** [comment]
That's not true, I am prevented from reporting on picassoTX and my reports were upheld
