### ISSUE TITLE
Site code unhelpfully disables reporting scripts if first report was dismissed

### ISSUE THREAD

**Issue by adamlui** [greasyfork-org/greasyfork#1295]
As revealed in https://github.com/greasyfork-org/greasyfork/issues/1294 (which you strangely close even though it's still a valid issue) "[i]t applies only when the **initial report is dismissed** or still pending and lasts for a month."

However, in https://github.com/greasyfork-org/greasyfork/issues/1290 (which you also strangely close) I helpfully revealed this restriction + a 1st report was wrongfully dismissed + a 2nd report was rightfully upheld

So if the intention is to "prevent harassment" as you justified, such intent is not actually being fulfilled since a followup report that is upheld (twice in my case I think) means no "harassment" occurred but a legit, valid issue with script that hurts the site was verified by actual employees as indicated by Upheld status, thus this condition for disabling reporting function needs to be fixed (I can provide more scenarios in which this is extremely useless and rather harmful at your request)

**Comment by JasonBarnabe** [comment]
The system is working as intended. Stop filing issues about it.

**Comment by adamlui** [comment]
But I'm saying it's not because harassment wasn't prevented, instead a spammer is allowed to continue with antifeature matching against rule, so the condition just needs a slight tweaking is all. May I suggest new ones please sir?

**Comment by adamlui** [comment]
You said "prevent harassment" was the intention remember? How was it prevented if subsequent reports were upheld? (Only ":dismissed" ones can be potentially harassing)
