### ISSUE TITLE
I cannot delete my old account because i miswrittened the email

### ISSUE THREAD

**Issue by cinast** [greasyfork-org/greasyfork#1297]
help  
i speell `outlook` into... ![image](https://github.com/user-attachments/assets/5c07b8c8-88a4-4889-b028-36d2bd283142)  
and nothing can return...

![image](https://github.com/user-attachments/assets/a45a0175-6255-41c8-9374-13963c40a7f5)  
can @greasyfork help me delete the account? (I m surely that I registed last year and no other user use it)

**Comment by JasonBarnabe** [comment]
I've removed the extra account.
