### ISSUE TITLE
@+name Unrecognized link

### ISSUE THREAD

**Issue by leadra** [greasyfork-org/greasyfork#1299]
![image](https://github.com/user-attachments/assets/172de602-31bf-46cc-b072-2c2556fee6cb)

It seems that as long as there are spaces in the name, it cannot be recognized correctly.
Tried using [-] or lowercase or removing spaces doesn't work either

**Comment by JasonBarnabe** [comment]
That format for usernames with spaces is `@"User Name"`.

**Comment by leadra** [comment]
thank you!!
