### ISSUE TITLE
Language change not added to cookies

### ISSUE THREAD

**Issue by d-patyk** [greasyfork-org/greasyfork#1300]
Steps to reproduce:
1. Open site (https://greasyfork.org/)
2. Change language to some other
3. Open site again in new tab (https://greasyfork.org/)
4. Language was reset.

Solution: store chosen language in cookies, and when visiting https://greasyfork.org/, not https://greasyfork.org/LANGUAGE-CODE, set language stored in cookies.

**Comment by JasonBarnabe** [comment]
Language is controlled by three factors:

1. If you explicitly choose a language from a dropdown, then you switch languages, and all links (should) maintain this switch. If you open a new tab, this is not maintained.
2. If you're logged in, it will use the language set in your profile. This defaults to the language you were using when you registered.
3. Your browser's language settings.

I don't see the need to complicate this further with cookies. Either log in (and choose the proper language in your profile) or configure your browser to match your language preferences.
