### ISSUE TITLE
scrip bypass dont work on business3.cryptednews.space

### ISSUE THREAD

**Issue by erikovick** [greasyfork-org/greasyfork#1305]
hola el scrip de saltos de publicidad no funciona con esta web 
https://business3.cryptednews.space/navigating-car-insurance-tips-for-lowering-your-premiums-without-compromising-coverage/
https://business3.cryptednews.space

**Comment by JasonBarnabe** [comment]
Please submit feedback on the script's page. This repo is for Greasy Fork itself.
