### ISSUE TITLE
Please add webcache to CDN urls

### ISSUE THREAD

**Issue by Francklin** [greasyfork-org/greasyfork#1306]
Webcache CDN: https://www.webcache.cn
contains static accelerate services in china below:
cdnjs: https://cdnjs.webstatic.cn
npm: https://npm.webcache.cn
github(with other): https://code.webcache.cn/gh/
other: https://cdn.webcache.cn
font: https://font.alnk.cn , https://font.webstatic.cn
ajax: https://lib.webstatic.cn

Thanks.

**Comment by JasonBarnabe** [comment]
I have added some of these to https://greasyfork.org/en/help/cdns

**Comment by Francklin** [comment]
Thanks very much!

**Comment by Francklin** [comment]
Please correct that it is font.webstatic.cn, but is not font.webcache.cn. Thanks!

**Comment by JasonBarnabe** [comment]
Added font.webstatic.cn. I swear it was different before.

**Comment by Francklin** [comment]
Thanks!
