### ISSUE TITLE
Show my unlisted scripts in my favorites

### ISSUE THREAD

**Issue by maboroshin** [greasyfork-org/greasyfork#1307]
When I open my favorites, my private scripts are not showing up. The same is true for script sets.

**Comment by JasonBarnabe** [comment]
There is no concept of "private scripts" on Greasy Fork. There are unlisted scripts. Is this what you mean?

Can you provide some more info:
1. What script set are you referring to (provide a link)?
2. What scripts are not showing up?
3. Are you referring to scripts that you yourself authored?
4. Do you expect that others could see the scripts if they loaded your script set?

**Comment by maboroshin** [comment]
The term “private script” refers to “Unlisted user script”.

Sorry, I made a mistake because on Youtube and other places they call it "Private".

**Comment by JasonBarnabe** [comment]
Can you answer the other questions I posted? That will help me debug it.

**Comment by maboroshin** [comment]
Questions 1 and 4 were omitted for these two reasons.

As to which set of scripts I don't wish to disclose. I don't want to associate it with my user name on GitHub.

I'm not referring to others loading script sets. At my mention, I'm opening my own favorites.

**Comment by JasonBarnabe** [comment]
Can you sent the info to me at jason.barnabe@gmail.com?

**Comment by maboroshin** [comment]
Your unlisted scripts don't appear in your favorites. In the same account of yours, of course. It is also after you press the add to favorites button. I considered this to be the current behavior. In that case you can debug within your own environment.

**Comment by JasonBarnabe** [comment]
It's expected that unlisted scripts are not listed in script sets.

**Comment by maboroshin** [comment]
He asked a series of questions, so it was possible that it was a bug that was occurring uniquely to me. But it appears that was not the case.

He never once uses the word “favorites”. If I had to guess, I'd say it means this.

The unlisted scripts don't appear in their own favorites. The favorites that are only visible to me can only display scripts created by others.
