### ISSUE TITLE
Please add the CDN url

### ISSUE THREAD

**Issue by love336** [greasyfork-org/greasyfork#1309]
https://cdn.jsdelivr.net/npm/hls.js/dist/hls.min.js

thanks!

**Comment by JasonBarnabe** [comment]
https://greasyfork.org/en/help/cdns

You can only reference version-specific URLs for jsdelivr, for example https://cdn.jsdelivr.net/npm/hls.js@1.5.14/dist/hls.min.js. This is intentional to prevent the contents from being swapped out.
