### ISSUE TITLE
Source code synchronization related Chinese text errors.

### ISSUE THREAD

**Issue by jk278** [greasyfork-org/greasyfork#1314]
After setting the synchronization method to manual, the Chinese text "The script code is set to automatic synchronization.（脚本代码已设定为自动同步）" still appears above the synchronization URL. The correct text is "Manual synchronization.（手动同步）"

**Comment by JasonBarnabe** [comment]
The text in English in this case:

> This script's code is set up to sync from: [input field]

![image](https://github.com/user-attachments/assets/61c47662-9bd0-4270-9b09-29f5430ceb7b)

Does not say that the code will be synced automatically or manually - it is just specifying the source URL. The text immediately after is what says if it's manual or automatic.

If you'd like to suggest better text for this meaning, please do so. You can also just make changes at https://app.transifex.com/greasy-fork/greasy-fork/translate/#zh_CN/enyml-19/31881004

**Comment by jk278** [comment]
![IMG_20240901_030735](https://github.com/user-attachments/assets/7f589edd-491e-45d6-936c-0391ee786dbf)
Thank you for your reply. The above picture shows the appearance of the Chinese text. The part ***circled in red***, I think, is not accurate enough and misleading. It indicates the meaning of "automatic". A more appropriate translation should be "脚本代码已设定为从该链接同步：", that is, replace "自动" with "从该链接". After repeated deliberation, I think the new statement has no obvious problems and I hope it can be adopted.
