### ISSUE TITLE
帳號申訴／Banning Appeals （report #65735）

### ISSUE THREAD

**Issue by Sorrovv** [greasyfork-org/greasyfork#1315]
我不理解為什麼我的帳號被封禁，除了下載user scripts，這個帳號沒有過任何違規活動，也不發布user scripts，根本找不到封禁的理由。

I don't understand why my account was banned. Except for downloading user scripts, this account has not done any illegal activities, nor has it published user scripts. There is no reason for the ban at all.

![Screenshot 2024-09-01 at 12-21-20 Greasy Fork - safe and useful user scripts](https://github.com/user-attachments/assets/fd6857b3-3052-4984-abb8-17791bf7f667)

![Screenshot 2024-09-01 at 12-19-09 Greasy Fork - 安全且实用的用户脚本站](https://github.com/user-attachments/assets/53d97b2c-92bf-4a69-9a59-0a05ecbc4107)

**Comment by JasonBarnabe** [comment]
Your account posted several user scripts that were direct copies of existing scripts.

**Comment by Sorrovv** [comment]
> 您的帳戶發布了多個使用者腳本，這些腳本是現有腳本的直接副本。

我很少登入帳號，頂多收藏自己安裝的腳本，避免找不到。另外我完全不懂代碼，我不認為我有能力發布多個使用者腳本。

**Comment by Sorrovv** [comment]
> Your account posted several user scripts that were direct copies of existing scripts.

我不會寫user scripts，一年中可能只登入帳號2、3次，封禁帳號前，你應該先確認是否為本人操作，而不是直接封掉帳號。
