### ISSUE TITLE
Untranslated strings

### ISSUE THREAD

**Issue by maboroshin** [greasyfork-org/greasyfork#1317]
* [ ] `Conversion of user CSS to user JS` (Title bar) https://greasyfork.org/ja/help/user-js-conversions
* `Conversion of user CSS to user JS` = Already registered. ID: `help.user_css_to_user_js.title`
* [ ] `Script set`: (Right bar category) https://greasyfork.org/ja/scripts
* `Script sets` = Already registered. ID:  `sets_label_no_sets`
* [ ] `All` (Right bar category) Same URL
* "All" for sites and "All" for languages already exist. 
* [ ] `Authorship`: (Right bar category) Same URL

----
* [ ] `Script Sets` (User's top page) e.g. https://greasyfork.org/ja/users/291050-ankvps
* `Script sets` = Already registered. ID:  `script_sets.edit_sets.heading`
* [ ] `Edit` (User's top page:  Your own dashboard while logged in) Same URL
* [ ] `Edit` (My script set: Your own dashboard while logged in) Same URL and e.g. https://greasyfork.org/ja/scripts?set=337876
* `Edit` = There are already registrations in other contexts. ID: `edit_comment_link` 
* [ ] `Add script set` (New script set) https://greasyfork.org/ja/users/xxxxxx/sets/new
* [ ] `Favorite` (New script set- drop down menu) Same URL
* `Favorite` = "`Favorites`" ("S" added) is already registered. ID: `favorites_name`

----
* [ ] `Access denied.` (No login) https://greasyfork.org/ja/scripts/11057-block-youtube-users/admin
* [ ] `Checkup These are suggestions to ...` (Logged in)  Same URL
* May already be in preparation.

**Comment by JasonBarnabe** [comment]
Some things are intentionally not made translatable:

- Things related to script sets - these are deprecated and not shown to new users
- Error messages that do not occur with normal operation

Other things you have listed have been made translatable and show should up on [Transifex](https://app.transifex.com/greasy-fork/greasy-fork/dashboard/) within a day.
