### ISSUE TITLE
Resolve relative URLs correctly

### ISSUE THREAD

**Issue by PRO-2684** [greasyfork-org/greasyfork#1330]
I noticed that if you use relative URL for images, like `![](./image.jpg)`, it will render correctly on GitHub, as expected. But synced readmes on GreasyFork does not resolve this and gives an empty `<img>` tag. I suggest that GreasyFork should resolve the relative URL based on the provided readme URL.

**Comment by JasonBarnabe** [comment]
There is [code to do this](https://github.com/greasyfork-org/greasyfork/blob/bffb1fdc7964173de2c7b0104df6964a4bf51d5f/lib/script_importer/base_script_importer.rb#L103), but I'm guessing it only works when using HTML and not Markdown.

**Comment by PRO-2684** [comment]
> There is [code to do this](https://github.com/greasyfork-org/greasyfork/blob/bffb1fdc7964173de2c7b0104df6964a4bf51d5f/lib/script_importer/base_script_importer.rb#L103), but I'm guessing it only works when using HTML and not Markdown.

Is it possible to port this to Markdown? I think it would be great.

**Comment by JasonBarnabe** [comment]
This should work now. It will use the URL that you're syncing from as the base for relative URLs.
