### ISSUE TITLE
Update deleted scripts to new script does not work

### ISSUE THREAD

**Issue by reaseno** [greasyfork-org/greasyfork#1331]
I have deleted a script (https://greasyfork.org/en/scripts/511339-script-a-for-testing) with the option “What would you like to happen to users who previously installed your script? > They will be redirected and updated to the script you specify below”. Here I have specified the URL: https://greasyfork.org/en/scripts/511340-script-b-for-testing

Next, I went to the browser where the deleted script A is installed via GreasyFork with Tampermonkey. Then go to the script settings and clicked on “Check for userscript updates”. All I get is “No update found, sry!”

So the deleted script A is not replaced by the new script B in Tampermonkey. What am I doing wrong?

**Comment by JasonBarnabe** [comment]
There was an error in the code that led it to redirect to the wrong URL. Now it should be redirecting properly, e.g. https://update.greasyfork.org/scripts/511339/Script%20A%20for%20testing.meta.js to https://update.greasyfork.org/scripts/511340/Script%20B%20for%20testing.meta.js

**Comment by JasonBarnabe** [comment]
It's possible that the replacement script needs to have a version number higher than the original for Tampermonkey to do the update.

**Comment by reaseno** [comment]
Right, I had forgotten that. Now it works. Thanks for that and many thanks for the great platform and your work 👍
