### ISSUE TITLE
Username update only saved for current session [bug]

### ISSUE THREAD

**Issue by warrengalyen** [greasyfork-org/greasyfork#1335]
When I update my username after logging in with my Github account, it stays updated for the current session . But when I'm logged out and log back in, my username is reset to my Github username. This happens everytime.

**Comment by JasonBarnabe** [comment]
Go to https://greasyfork.org/en/users/edit_sign_in, turn off syncing, then it will no longer automatically update your username.

**Comment by warrengalyen** [comment]
Thanks for the quick response!
