### ISSUE TITLE
The script has been reported for review. I cannot see the content of the report notification and I have not received it in my email

### ISSUE THREAD

**Issue by AFANOOO** [greasyfork-org/greasyfork#1339]
My script has been reported for review. Why can't I see the content of the report notification and haven't received it in my email
![微信截图_20241112151242](https://github.com/user-attachments/assets/b9dccdcc-fcd3-41b2-aee1-8ccc0e27ff3a)

**Comment by JasonBarnabe** [comment]
I presume [this](https://greasyfork.org/en/reports/74286) is the report, which is now dismissed. Not sure why there were no notifications. I'll look into that.

**Comment by JasonBarnabe** [comment]
Closing per above.
