### ISSUE TITLE
Suggestion to improve script upload checks to prevent bypassing restrictions

### ISSUE THREAD

**Issue by hmjz100** [greasyfork-org/greasyfork#1340]
I’ve noticed that some scripts that violate platform policies are getting through simply by changing their name or a few details, while the core functionality remains unchanged. One way to prevent this could be to record the "clean code" of flagged scripts (removing metadata and formatting the code), and then, when users upload new scripts, clean their code as well and compare it to the clean version of the flagged scripts. If it matches, it should trigger a warning and prevent the upload.

**Comment by JasonBarnabe** [comment]
This kind of check is already done and when it's detected, a report gets sent for moderators to review.

**Comment by hmjz100** [comment]
From my perspective, this check seems to be performed automatically by a bot. I’ve noticed that after the bot triggers a report with the message “Script is similar to previously deleted scripts,” the reported script is not immediately hidden from the website. As a result, regular users can still view or install the flagged script before a decision is made by the moderators. It would be better if the check could be performed immediately after clicking the "Publish" button. This way, it could instantly prevent the creation of new scripts that violate the rules.

**Comment by hmjz100** [comment]
Hmm, that's actually a good approach. However, I have another idea that might be even better. We could introduce a new "Script Type" similar to the "Unlisted user script" mode, where the script wouldn't be publicly displayed. But unlike the "Unlisted user script," it wouldn't show up as "Unlisted" to the user who uploaded the flagged script. Instead, it would appear as a "Public user script" to them, further confusing the person trying to bypass the system.

**Comment by JasonBarnabe** [comment]
The automated check is not perfect - sometimes short scripts get flagged, sometimes scripts that have a large library embedded get flagged, etc. While it's good to confuse spammers, I really don't want to confuse legitimate users.

If a trusted user reports the script, then what you describe happens.
