### ISSUE TITLE
Mobile browser support updates

### ISSUE THREAD

**Issue by derjanb** [greasyfork-org/greasyfork#1346]
Hi @JasonBarnabe,

I wanted to share two updates regarding mobile browser support:

## Microsoft Edge and Tampermonkey:

Microsoft Edge Android has recently added support for Tampermonkey. If users install it via [this link](https://www.tampermonkey.net/qr/e) on an Android device, Edge will even come pre-configured to streamline Tampermonkey installation.

## Tampermonkey for Safari (which now also supports iOS):

I charge a small fee for the Safari version of Tampermonkey due to the additional costs of purchasing hardware and the higher complexity of supporting Safari compared to other browsers.
That said, [I do offer free licenses to developers](https://www.tampermonkey.net/promo.php) of popular scripts. If you think this information is relevant then please add it where you see fit on GreasyFork.

BTW: I added QR codes that can be scanned with a mobile device to make it easier for users to follow links on tampermonkey.net. This could be a nice addition to the GreasyFork site as well.

![image](https://github.com/user-attachments/assets/72c43946-38e6-4108-8202-567427211e0e)

**Comment by JasonBarnabe** [comment]
On the homepage at https://greasyfork.org and in a modal when the user attempts to install a script and we can't detect an extension, we already provide links to Tampermonkey.

## Homepage

- Desktop Edge - https://microsoftedge.microsoft.com/addons/detail/tampermonkey/iikmkjmpaadaobahmlepeloendndfphd
- Android Edge - **no TM link**
- Desktop Safari - http://tampermonkey.net/?browser=safari - **update to canonical https://www.tampermonkey.net/?browser=safari**
- IOS Safari - http://tampermonkey.net/?browser=safari - **update to canonical https://www.tampermonkey.net/?browser=safari**

## Install modal

- Edge - **No links at all**
- Safari - **Entry for Tampermonkey, but looks like it's pointing to the Opera store instead.**

I will fix the bolded items above. I want this just to be a straight link to the easiest installation method, so if you think some links should point elsewhere, let me know and I can update.

**Comment by derjanb** [comment]
Yes, maybe one more thing:

Kiwi links to https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo which is not working, because [Kiwi added incomplete MV3 support](https://github.com/kiwibrowser/src.next/issues/1135). So it's better to use [Tampermonkey Legacy](https://chromewebstore.google.com/detail/tampermonkey-legacy/lcmhijbkigalmkeommnijlpobloojgfn) (which is and stays a MV2 extension) instead. 

Thanks.

**Comment by JasonBarnabe** [comment]
Made that update too.
