### ISSUE TITLE
FireMonkey: `window.external`

### ISSUE THREAD

**Issue by erosman** [greasyfork-org/greasyfork#1348]
Hi Jason

Subsequent to [[FireMonkey] Please add Firemonkey to window.external](https://github.com/erosman/support/issues/582), I have been working on a solution.

The outcome so far is as following:

### window.external.FireMonkey
```js
{
  version: '2.74',
  isInstalled() { }
}
```
- available on `greasyfork.org` & `sleazyfork.org`
- available on `/scripts/*` & `/scripts/*/code`
- not available on other pages i.e. `/scripts`, `/scripts/*/feedback`, `/scripts/*/stats`, `/scripts/*/versions`
- FM gets the required data asynchronously on `"document_start"`
- data can then be accessed by GF synchronously

### Examples
```js
!!window.external?.FireMonkey
// true or false

window.external.FireMonkey.version
// "2.74"

window.external.FireMonkey.isInstalled()
// "1.2.3" or undefined
```

### isInstalled()

-  used to resembles VM|TM methods but data can also be provided as a property _(which could be better)_
```js
window.external.FireMonkey.isInstalled
// "1.2.3" or undefined
```
- returns synchronously, unlike VM|TM
- does not require an argument
- data is only provided for the script on that page
- FM provides data based on installation URL i.e. checks if an installed script has the installation URL that starts with `https://update.${hostname}/scripts/${id}/`

Please let me know if there are any comments and I can then upload the current beta for testing.

Note: I created a dedicated [FireMonkey](https://github.com/erosman/firemonkey) repository.

**Comment by JasonBarnabe** [comment]
How does `isInstalled` know which script it should be returning info about? The Tampermonkey and Violentmonkey versions of this function accept name and namespace as parameters.

**Comment by JasonBarnabe** [comment]
Greasy Fork currently uses installation URLs as you describe but in the past it was different. Would scripts previously installed at different URL formats not work then? It also may change again in the future - would this break any previous installs and require an update to FireMonkey?

I assume you are taking into account that Greasy Fork has locale-based URLs, and also that the canonical URL of a script may change (though the ID portion would not).

**Comment by erosman** [comment]
I noticed that and had to update some other code to `update.greasyfork.org`.

If FM cant find a userscript based on the installation URL, it will be treated as a new userscript. However, when saving the userscript, it will overwrite the older one, as long as its `@name` hasn't changed.
Therefore, its installation URL will be updated (for the next time).

---

What do you think about property instead of method? 
_(the property name can be decided)_

```js
{
  version: '2.74',
  isInstalled: '1.2.3'   // or undefined
}
```

**Comment by JasonBarnabe** [comment]
Property vs function doesn't really matter to me. With Tampermonkey and Violentmonkey it's an asynchronous function, but this is because we have to provide info on the script. If FireMonkey is gonna be responsible for figuring out which script it is, and there are no performance considerations, then a property would work.

**Comment by erosman** [comment]
I have updated the code to look for both new & old installation URL formats.
I have uploaded the latest beta to the FireMonkey repo.
You can try it and let me know how it works out.

It is outputting properties.

**Comment by erosman** [comment]
At the moment it outputs
```js
{
  version: '2.74',
  isInstalled: '1.2.3'   // or undefined
}
```

However, I am fine with anything you like.
I can change it to `installedScriptVersion`.
Do you want to change it?

**Comment by JasonBarnabe** [comment]
Yes please, I think that makes it clearer.

**Comment by erosman** [comment]
Done and repo updated.
You can try it and let me know.

**Comment by JasonBarnabe** [comment]
I've blind-implemented the logic on Greasy Fork. I'm not sure where to get a version of FireMonkey to test with.

**Comment by erosman** [comment]
I tried it now and it is working

![image](https://github.com/user-attachments/assets/aa110b06-8ef5-4eca-a8f7-2b67ff1d9c3f)



> Note: I created a dedicated [FireMonkey](https://github.com/erosman/firemonkey) repository.

You can ..
- Download the repo as zip and extract (or `git` to your computer)
- With Firefox Nightly (or Developer Edition) go to `about:debugging#/runtime/this-firefox`
- Click on "Load Temporary add-on..."
- Find the `manifest.json` in the above extraction in `/src`

**Comment by JasonBarnabe** [comment]
OK if you say it's working I'll close this issue out. Thanks for adding the integration.

**Comment by erosman** [comment]
Just a note...
`versioncheck.js` doesn't cater for users who have installed more than one userscript manager.

Example:
![image](https://github.com/user-attachments/assets/a36df99e-e69a-421c-8876-44206e8e9378)

**Comment by JasonBarnabe** [comment]
I'm not sure of the behaviour when installing if you have multiple script managers. I wrote it assuming people only had one. If you've got multiple, Greasy Fork will reflect the script installation status of the first of TM, VM, and FM that you have installed.

**Comment by erosman** [comment]
It was only a note. :)

Most people only use one manager. 
However, some may use two as some scripts only work with one manager.
Furthermore, there is a race issue between managers when install button is clicked and no guarantee which one picks it up first.

AFA GreasyFork and displaying the information, you can try something like the following.

Resolving when there is an installed version, or continuing to the next.

```js
function getInstalledVersion(name, namespace) {
  return new Promise(function(resolve, reject) {
    const tm = getTampermonkey();
    if (tm) {
      tm.isInstalled(name, namespace, function (i) {
        if (i.installed) {
          resolve(i.version);
        }
      });
    }

    const vm = getViolentmonkey();
    if (vm) {
      vm.isInstalled(name, namespace).then(i => i && resolve(i));
    }

    const fm = getFiremonkey();
    if (fm) {
      resolve(fm.installedScriptVersion || null);
    }
    
    reject();
  });
}
```

**Comment by cyfung1031** [comment]
@JasonBarnabe  @erosman 

Thanks for your feature adding.

I have tested that it is worked in my Firefox. However, just one thing want to mention. It would be great that you guys can do some improvement on this issue.

### Issue

After clicking the installation button, the installed status will not be reflected to the greasyfork page. It requires manual refresh.

### Proposed idea

#### Firemonkey
Firemonkey actively update the property value for the current greasy fork page. So it can let greasyfork page to obtain the latest installation status after installation.
Then, GreasyFork just need a delay after clicking button for the checking latest status using `window.external`
(say 2 seconds)

#### Other userscript managers

For other userscript managers, they will open a new tab for the installation. so once the user is returned to the greasyfork page, greasyfork can check the installation status.
(for simplicity, just use `requestAnimationFrame`)


### Pseudo Code

```
setTimeout(() => {
  requestAnimationFrame(() => {
    // check installation status again.
  });
}, 2000);
```

**Comment by erosman** [comment]
> After clicking the installation button, the installed status will not be reflected to the greasyfork page. It requires manual refresh.

Clicking the button does not always lead to installation:

- Users still have the option to cancel on confirmation popup
- FireMonkey wont update the script if the version number on GF is the same or lower than the one installed
- Installation can fail if there are errors

**Comment by cyfung1031** [comment]
> > After clicking the installation button, the installed status will not be reflected to the greasyfork page. It requires manual refresh.
> 
> Clicking the button does not always lead to installation:
> 
> * Users still have the option to cancel on confirmation popup
> * FireMonkey wont update the script if the version number on GF is the same or lower than the one installed
> * Installation can fail if there are errors

Yes. I understand.

Just if the installation is successful, then update the property for the page without manual refresh.
GF can check whether there is any change in the installation status by time delay.
