### ISSUE TITLE
Idea: Add pre with raw code to Info & Code tabs

### ISSUE THREAD

**Issue by erosman** [greasyfork-org/greasyfork#1349]
Hi Jason

It is just an idea ......

At the moment, ...

- Install button is available on the script Info & Code tabs
- Code tab also includes the actual code
- On Code tab, `pre.uglyprint` is changed to `pre.prettyprint` if code is not too long
- The `textContext` appears to remain the same after `prettyprint` 

After clicking the install button, FireMonkey gets the script via `fetch`. I have not checked the other managers but their process might be similar.

Since the code is already present in the Code tab, I was thinking that it would be beneficial for reducing the process & load, for both the script manager and Greasy Fork, by getting the code from the DOM.

By adding a hidden `pre` to both the script Info & Code tabs with the plain script code, I can update FireMonkey to perform the installation directly from the DOM and avoid the additional `fetch`.

**Comment by JasonBarnabe** [comment]
While this would avoid an additional request, it would require every request to be much heavier, and it's likely to slow the site down.

**Comment by erosman** [comment]
I see..... fair enough.
