### ISSUE TITLE
Wrong Site Title

### ISSUE THREAD

**Issue by cyfung1031** [greasyfork-org/greasyfork#1352]
https://sleazyfork.org/en/discussions

<img width="754" alt="Screenshot 2024-12-09 at 4 14 59" src="https://github.com/user-attachments/assets/184f2c0f-e8f2-4783-bca9-6148302b47c0">

**Comment by JasonBarnabe** [comment]
Fixed by 2ac5c90033df5c749752aec3907a9c78673d23aa
