### ISSUE TITLE
CSS to JS converter

### ISSUE THREAD

**Issue by erosman** [greasyfork-org/greasyfork#1356]
I was looking at examples on greasyfork and I noticed the following:

https://greasyfork.org/en/scripts/403111-fandom-remove-garbage

```CSS
@-moz-document domain("fandom.com") {
  /* ... */
}
```
converted to:
```js
// @include http://fandom.com/*
// @include https://fandom.com/*
// @include http://*.fandom.com/*
// @include https://*.fandom.com/*
```

In case of `domain()`, the following should cover it and be more efficient.

```js
// @match *://*.fandom.com/*
```

**Comment by JasonBarnabe** [comment]
Would `*://*.example.com/*` match a URL on the root domain like `http://example.com/`? Could it potentially match other protocols?

Other kinds of `@-moz-document` rules also turn into `@include` rules, and they are deduplicated, so rewriting the domain example to use `@match` could result in redundant rules unless the other types are also converted into `@match`, but I don't think that's possible in all cases.

**Comment by erosman** [comment]
> Would `*://*.example.com/*` match a URL on the root domain like `http://example.com/`?

[Match patterns](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns) is designed as such.

> `*://*.mozilla.org/*`
> 
> Match all HTTP, HTTPS and WebSocket URLs that are hosted at "mozilla.org" or one of its subdomains. 

> Could it potentially match other protocols?

Protocol wildcard would "Match all HTTP, HTTPS and WebSocket URLs."
It is standard practise to use protocol wildcard for content and user scripts and there should not be any significant concern over the WS/WSS in this case.



> Other kinds of `@-moz-document` rules also turn into `@include` rules, and they are deduplicated, so rewriting the domain example to use `@match` could result in redundant rules unless the other types are also converted into `@match`, but I don't think that's possible in all cases.

`@match` can be directly passed to `matches` in the API which is more performant.

In FireMonkey,, `url()`, `url-prefix()`, `domain()` are converted to match patterns.

Only `regexp()` remains which is not supported by any browser API. User script managers accept them in `@include` but have to manually inject them.

```
url(value)            -> @match  `${value}`
url-prefix(value)     -> @match  `${value}` + (value.split(/:?\/+/).length > 2 ? '*' : '/*') // fix no path
domain(value)         -> @match  `*://*.${value}/*`

regexp(value)         -> @include  `${value}`
```

**Comment by JasonBarnabe** [comment]
Fixed in b5858cedd1272db50539abc3795089d62864d0f1.

**Comment by erosman** [comment]
Please note the following which I didn't see in the modifications:

`url-prefix(value)` can run into issues if the URL doesn't have a path e.g.
```
url-prefix('https://example.com')
```

It should be converted to 
```
@match  https://example.com/*
```


Also the following in the [‎test/lib/css_to_js_converter_test.rb](https://github.com/greasyfork-org/greasyfork/commit/b5858cedd1272db50539abc3795089d62864d0f1#diff-5226155ada317cb4f1b41f2537e362cf0d3b9cfd0952f129e9e4c0ed828a0e31) is not valid match pattern
```
// @match *
```

It should be 
```
// @match   *://*/*
```

**Comment by JasonBarnabe** [comment]
Thanks for checking; I've made those adjustments.

**Comment by erosman** [comment]
A little thing that you may consider changing....

```js
      if (typeof GM_addStyle !== "undefined") {
        GM_addStyle(css);
      } else {
        let styleNode = document.createElement("style");
        styleNode.appendChild(document.createTextNode(css));
        (document.querySelector("head") || document.documentElement).appendChild(styleNode);
      }
```

Since `styleNode` does not change, `const` would be better.

**Comment by erosman** [comment]
re: https://greasyfork.org/en/scripts/422285-google-translate-dark

I noticed another issue with `url-prefix(value)`. 
`@match` can not be used with incomplete domains (e.g. missing TLD).
Even with `@include` (i.e. `includeGlobs`) it requires some extra steps.

### `url-prefix("https://translate.google.")`

if value doesn't have a path and ends in `.`, it must be converted to
```
@include   `#{value}*/*`
```

Therefore ...
`url-prefix("https://translate.google.")` converts to `@include   https://translate.google.*/*`

**Comment by erosman** [comment]
re: 
https://greasyfork.org/en/scripts/396868-disable-all-css-animations
https://greasyfork.org/en/scripts/439627-global-ads-and-cookie-banner-remover

Another issue with missing `@-moz-document`

When there is no `@-moz-document`
- add `// @match   *://*/*`
- use the rest of CSS

**Comment by erosman** [comment]
Another little thing that you may consider changing.... same thing but a bit shorter

```js
if (typeof GM_addStyle !== "undefined") {
  GM_addStyle(css);
} else {
  const styleNode = document.createElement("style");
  styleNode.textContent = css;
  (document.head || document.documentElement).appendChild(styleNode);
}
```

**Comment by JasonBarnabe** [comment]
Thanks for continuing to test this. In the future, it may be easier to just create separate issues in GitHub so it's easier to keep track of things.

Regarding `url-prefix`, if we take cases where there is no slash to begin the path portion, it could be one of the following:

1. A TLD wildcard, for example [this style](https://greasyfork.org/en/scripts/422285-google-translate-dark/code) and `url-prefix("https://translate.google.")`- we should do `@include https://translate.google.*/*`. This is detectable by a dot being the last character.
2. A complete domain, for example [this style](https://greasyfork.org/en/scripts/426513-google-translate-dark-theme/code) and `url-prefix("https://ogs.google.com")` - we should do `@match https://ogs.google.com/*`.
3. A domain wildcard, for example [this style](https://greasyfork.org/en/scripts/409167-mastodon-cyberpunk-neon/code) and `url-prefix("https://masto")`, presumably intending to match `https://mastodon.com` as well as `https://mastoanythingelse.com` - not sure what to do here - does `@include https:://masto*/*` work?

There doesn't seem to be a perfect rule to differentiate between 2 and 3. I could check to see if it looks like it has a valid TLD, which should get it almost entirely right, but could fail on things like `url-prefix(https://mysite.com)` actually intending to match `https://mysite.company.org`.

Even for 1 it's not guaranteed that they intended to mean a TLD - perhaps `url-prefix(https://example.*)` is supposed to match `url-prefix(https://example.site.com)`.

Any thoughts?

**Comment by erosman** [comment]
> it may be easier to just create separate issues in GitHub so it's easier to keep track of things.

You can also keep this topic open for everything regarding the converter. 

> Any thoughts?

After considering all the possibilities in  `url-prefix()`, it seem the only option that covers all would be:
- If there is no pathname, convert to `@include   ${value}*/*`
- If there is a pathname, convert to `@match   ${value}*`

That is how the original `url-prefix()` in the UserStyle would work.

**Comment by erosman** [comment]
re: https://github.com/greasyfork-org/greasyfork/commit/182916b3f311d12effaac0f8ee2837bac4c50566

I am not familiar with Ruby but I think an extra check is needed

```ruby
if !value.include?('://')
# disregard poorly written rule

elsif value.count('/') == 2
# missing path, use @include

else 
# with path, use @match
end
```

**Comment by erosman** [comment]
Out of curiosity, these UserStyles convert to UserScripts easily. How come the don't have a "Install this script" button?

https://greasyfork.org/en/scripts/404191-classic-green
https://greasyfork.org/en/scripts/404192-small-thumbnails
https://greasyfork.org/en/scripts/404193-small-thumbnails-no-background
https://greasyfork.org/en/scripts/404194-small-thumbnails-visible-titles
https://greasyfork.org/en/scripts/405929-rarbg-dark-theme
