### ISSUE TITLE
Why this external code url is not allowed?

### ISSUE THREAD

**Issue by cyfung1031** [greasyfork-org/greasyfork#1357]
I want to import the following userscript to Greasy Fork:
https://raw.githubusercontent.com/cyfung1031/userscript-supports/main/boost-chat.user.js

It uses the library
https://raw.githubusercontent.com/cyfung1031/userscript-supports/b020bbb73dfa65d72b4656596f8e9ff1549becd6/library/solid-js-prod.js

I cannot import the userscript due to the external code url is not allowed. Why this url is not allowed?

<img width="669" alt="Screenshot 2024-12-15 at 0 24 18" src="https://github.com/user-attachments/assets/28cc0587-25ea-4c2a-b35a-80eb015cdc06" />

**Comment by JasonBarnabe** [comment]
GitHub is not a CDN. You can either set up this JS through something like [jsDelivr](https://www.jsdelivr.com/) or by adding it as a library on Greasy Fork.

**Comment by cyfung1031** [comment]
> GitHub is not a CDN. You can either set up this JS through something like [jsDelivr](https://www.jsdelivr.com/) or by adding it as a library on Greasy Fork.

I agree GitHub link is not CDN.

But as it does have commit id, it cannot be changed after the installation of userscript.

Why it has to be CDN link?
