### ISSUE TITLE
@include CDN request

### ISSUE THREAD

**Issue by wish13yt** [greasyfork-org/greasyfork#1361]
jsDelivr is said to be supported, but https://cdn.jsdelivr.net/npm/ doesn't work.
![image](https://github.com/user-attachments/assets/5a376325-14cc-448d-8a42-404f698035ce)
![image](https://github.com/user-attachments/assets/d29fe34d-cf9d-471b-9730-8de81a423462)

**Comment by JasonBarnabe** [comment]
The pattern at https://greasyfork.org/en/help/cdns requires further characters after /npm/. What is the actual URL you're trying to use in your script?

**Comment by wish13yt** [comment]
> The pattern at https://greasyfork.org/en/help/cdns requires further characters after /npm/. What is the actual URL you're trying to use in your script?

Thanks for responding so quickly! The URL I'm trying to use is https://cdn.jsdelivr.net/npm/@twemoji/api@latest/dist/twemoji.min.js, aka jdecked's Twemoji library.
Sorry if I'm doing anything wrong, I'm new to userstyles

**Comment by JasonBarnabe** [comment]
You are required to use a version-specific URL, not one with "latest".

**Comment by wish13yt** [comment]
> You are required to use a version-specific URL, not one with "latest".

thanks for the help :D
